netuid: 197
neuron:
  device: is_cuda_available()
  epoch_length: 100
  events_retention_size: 2 * 1024 * 1024 * 1024
  dont_save_events: false
  name: razor_test
  timeout: 10
  num_concurrent_forwards: 5
  sample_size: 50
  disable_set_weights: false
  moving_average_alpha: 0.1
  vpermit_tao_limit: 4096
mock: false
wandb:
  'off': true
  offline: true
  notes: '""'
  project_name: '""'
  entity: '""'
blacklist:
  force_validator_permit: true
  allow_non_registered: false
axon_off: false






















