# Embedding module configuration for development environment

# Model configuration
model:
  name: 'facebook/seamless-M4T-V2-large'
  max_length: 6400
  batch_size: 32
  model_type: 'vocoder_v2'

# Preprocessing configuration
preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_stopwords: false

# Postprocessing configuration
postprocessing:
  normalize: true
  dimensionality_reduction: null

# Performance settings
performance:
  use_gpu: true
  num_workers: 2

# Override default module settings if needed
max_input_length: 10000
cache_results: false

requirements:
  - numpy==2.0.1
  - requests==2.32.3
  - SQLAlchemy==2.0.32
  - python-dotenv==1.0.1
  - config-yaml==0.0.2
  - scipy==1.14.0
  - torch